# P20 — Preference-Aware Router (Mocking Version)

- ID: P20-mocking
- Folder: `projects/p20-preference-aware-router-mocking`
- Status: draft
- Module: `m03_sessions_memory`

This is the **mocking version** of the Preference-Aware Router. It demonstrates the chain:

> **P18 — Preference Extraction** → **P19 — Preference-Aware Persona** → **P20 — Routing (Mock)**

No real ADK LlmAgent calls are made here. Instead, we load the Persona from P19 and route to one of two simulated agents.

---

## Concept: Persona → Policy → Mock Agent

The router answers: “Given this Persona, what agent behavior should we choose?”

Inputs inspected:
- `answer_style`
- `format_preferences`
- `dislikes`

Policy derived (examples):
- `prefer_structured_output`
- `prefer_code_examples`
- `avoid_marketing_style`
- `default_agent = structured_agent | narrative_agent`

Mock agents:
- `structured_agent_respond()` — structured, bullet-point output.
- `narrative_agent_respond()` — narrative, exploratory output.

---

## Project Structure

```text
projects/p20-preference-aware-router-mocking/
├── README.md
├── project.card.yaml
├── persona_state.json        # Input generated by P19
└── src/
    └── main.py               # Full pipeline: load persona → derive policy → pick agent → respond
```

---

## How to Run

From repository root `adk-decade-of-agents/`:
1) Activate venv: `source .venv/bin/activate` (prompt should show `(.venv)`).
2) Execute: `cd projects/p20-preference-aware-router-mocking/src && python main.py`.
   - Alternatively, run from project root and adjust the path: `python src/main.py`.

---

## Expected Output (sample)

```
🚀 P20 — Preference-Aware Router v1 started
📥 Loading persona from: /Users/Agent/adk-decade-of-agents/projects/p20-preference-aware-router-mocking/persona_state.json
✅ Persona loaded successfully.

🎭 Persona Signals
------------------
- answer_style: concise, highly structured answers with clear reasoning and examples
- format_preferences: ['bullet_points', 'code_examples', 'clear_reasoning']
- dislikes: ['noisy_ux', 'over_marketing', 'vague_explanations']

🧭 Routing Decision
-------------------
- prefer_structured_output: True
- avoid_marketing_style: True
- prefer_code_examples: True
- default_agent: structured_agent
→ selected agent: structured_agent

🤖 Agent Response
-----------------
Structured Agent Response
- Style: concise, highly structured answers with clear reasoning and examples
- Known interests: reading_sci_fi, building_agent_projects, math_logic_games_with_children

Answer to: Explain what this ADK project does for the next decade of agents.
1) First, summarize the core idea.
2) Then, break it into clear, ordered steps.
3) Finally, suggest one concrete next action.

🏁 P20 — Preference-Aware Router v1 finished
```

Persona fields vary with `persona_state.json`, but the printed sections (persona signals, policy, selected agent, response shape) should remain consistent.

---

## Files Touched

- Input: `persona_state.json` (read only)
- Output: console logs only (optionally add `routing_log.json` in future)

---

## Development Loop

1) Activate venv: `source .venv/bin/activate`
2) Enter project: `cd projects/p20-preference-aware-router-mocking`
3) Run: `cd src && python main.py`
4) Verify: no crashes; persona loads; policy is reasonable; selected mock agent matches expectations
5) Commit from repo root:
   - `git add .`
   - `git commit -m "P20-mocking: add preference-aware routing demo with mock agents"`

---

## Relationship to P20 “Real Agent” Version

This mocking version is self-contained. A future real version can:
- Reuse the routing logic
- Replace mock agents with ADK `LlmAgent` calls
- Inject Persona into system prompts or session state
- Persist routing decisions (e.g., `routing_log.json`)

The goal here is to validate **Persona → Policy → Routing** before integrating real agents and tools.
